// <auto-generated />
namespace BookmarkManager.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddBookmarkPosition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBookmarkPosition));
        
        string IMigrationMetadata.Id
        {
            get { return "201208242006318_AddBookmarkPosition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
